export const defaultPrefs = {
  autoConvert: 0,
  iconAction: 1,
  inputConvert: 0,
  symConvert: true,
  fontCustomEnabled: false,
  fontCustomTrad: 'PMingLiU,MingLiU,新細明體,細明體',
  fontCustomSimp: 'MS Song,宋体,SimSun',
  contextMenuEnabled: true,
  contextMenuInput2Trad: true,
  contextMenuInput2Simp: true,
  contextMenuPage2Trad: true,
  contextMenuPage2Simp: true,
  contextMenuClip2Trad: true,
  contextMenuClip2Simp: true,
  urlFilterEnabled: false,
  urlFilterList: [],
  userPhraseEnable: false,
  userPhraseTradList: {},
  userPhraseSimpList: {},
  version: 1,
};

export const prefsValidKeys = [
  { key: 'autoConvert', type: 'number' },
  { key: 'iconAction', type: 'number' },
  { key: 'inputConvert', type: 'number' },
  { key: 'symConvert', type: 'boolean' },
  { key: 'fontCustomEnabled', type: 'boolean' },
  { key: 'fontCustomTrad', type: 'string' },
  { key: 'fontCustomSimp', type: 'string' },
  { key: 'contextMenuEnabled', type: 'boolean' },
  { key: 'contextMenuInput2Trad', type: 'boolean' },
  { key: 'contextMenuInput2Simp', type: 'boolean' },
  { key: 'contextMenuPage2Trad', type: 'boolean' },
  { key: 'contextMenuPage2Simp', type: 'boolean' },
  { key: 'contextMenuClip2Trad', type: 'boolean' },
  { key: 'contextMenuClip2Simp', type: 'boolean' },
  { key: 'urlFilterEnabled', type: 'boolean' },
  { key: 'urlFilterList', type: 'object' },
  { key: 'userPhraseEnable', type: 'boolean' },
  { key: 'userPhraseTradList', type: 'object' },
  { key: 'userPhraseSimpList', type: 'object' },
  { key: 'version', type: 'number' },
];
